package(default_visibility = ["//visibility:public"])

cc_library(
    name = "jni",
    hdrs = glob(["java_home/include/**/*.h"]),
    includes = [
        "java_home/include",
        "java_home/include/linux",
    ],
)
