/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uw_neuralccg_model_TreeFactoredModel */

#ifndef _Included_edu_uw_neuralccg_model_TreeFactoredModel
#define _Included_edu_uw_neuralccg_model_TreeFactoredModel
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_uw_neuralccg_model_TreeFactoredModel_AGENDA_DEPS
#define edu_uw_neuralccg_model_TreeFactoredModel_AGENDA_DEPS 0L
#undef edu_uw_neuralccg_model_TreeFactoredModel_PARSE_DEPS
#define edu_uw_neuralccg_model_TreeFactoredModel_PARSE_DEPS 1L
#undef edu_uw_neuralccg_model_TreeFactoredModel_USE_ENSEMBLE
#define edu_uw_neuralccg_model_TreeFactoredModel_USE_ENSEMBLE 1L
#undef edu_uw_neuralccg_model_TreeFactoredModel_BEST_FIRST
#define edu_uw_neuralccg_model_TreeFactoredModel_BEST_FIRST 0L
/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    initializeCNN
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_initializeCNN
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    initializeScorer
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_initializeScorer___3B
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    initializeScorer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_initializeScorer__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    initializeTrainer
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_initializeTrainer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    saveCheckpoint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_saveCheckpoint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    initializeSentence
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_initializeSentence
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    initializeSentenceWithGates
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_initializeSentenceWithGates
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    scoreAndBuildRepresentation
 * Signature: ([B)F
 */
JNIEXPORT jfloat JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_scoreAndBuildRepresentation
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    scoreAndBuildRepresentationWithGates
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_scoreAndBuildRepresentationWithGates
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_neuralccg_model_TreeFactoredModel
 * Method:    applyUpdate
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_uw_neuralccg_model_TreeFactoredModel_applyUpdate
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_uw_neuralccg_model_TreeFactoredModel_TreeFactoredModelFactory */

#ifndef _Included_edu_uw_neuralccg_model_TreeFactoredModel_TreeFactoredModelFactory
#define _Included_edu_uw_neuralccg_model_TreeFactoredModel_TreeFactoredModelFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
